# file: ansible-role-rapidcheck/tasks/compile-cppzmq.yml

- name: RC | check if RC is already installed
  stat:
    path: "{{ rc_install_dir }}/include/rapidcheck"
  #register: rc_exists

- name: RC | get from git repository
  git: repo="{{ rc_repo_url }}"
       dest="{{ rc_tmp }}"
       version="{{ rc_version }}"
  #when: not rc_exists.stat.exists
  # register: rc_downloaded

- name: RC | Make build folder
  become: true
  file: path="{{ rc_build_dir }}" state=directory
  # when: rc_downloaded.changed

- name: RC | cmake
  become: true
  command: chdir={{ rc_build_dir }} cmake -DRC_ENABLE_GTEST=ON -DCMAKE_INSTALL_PREFIX={{ rc_install_dir }} {{ rc_tmp }}
  # when: rc_downloaded.changed

- name: RC | make
  become: true
  command: chdir="{{ rc_build_dir }}" make
  # when: rc_downloaded.changed

- name: RC | install
  become: true
  command: chdir="{{ rc_build_dir }}" make install
  # when: rc_downloaded.changed

- name: Rc | cleanup build dir
  become: true
  file:
    path: "{{ rc_build_dir }}"
    state: absent
  # when: rc_downloaded.changed

- name: Rc | cleanup tmp dir
  become: true
  file:
    path: "{{ rc_tmp }}"
    state: absent
  # when: rc_downloaded.changed
